# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Default

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'mvn test'
  displayName: 'Execute Cucumber Tests'

- powershell: |
   $url = 'https://pulse-7.qtestnet.com/webhook/d06bdf36-07af-40c0-b6ef-b5c4e47166fb'
   
   $content = Get-Content "C:\TestAutomation\AzureDevOps\ADOagent\_work\1\s\target\cucumber-report.json" -Raw
   $bytes = [System.Text.Encoding]::ASCII.GetBytes($content)
   $payload = [System.Convert]::ToBase64String($bytes)
   
   $body = @{
    'projectId' = '123482'
    'testcycle' = '3089124'
    'result' = $payload
   }
   
   [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
   Invoke-RestMethod -Body $body -Method 'Post' -Uri $url
  displayName: 'Upload Results to qTest Pulse'